# Generated by Django 4.2.11 on 2024-03-18 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('cantidadAsistentesMaximo', models.IntegerField()),
                ('estatus', models.BooleanField(default=False, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.categorias')),
            ],
            options={
                'db_table': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidoPaterno', models.CharField(max_length=45)),
                ('apellidoMaterno', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.eventos')),
            ],
            options={
                'db_table': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='Qrs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='')),
                ('datos', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.eventos')),
            ],
            options={
                'db_table': 'Qrs',
            },
        ),
        migrations.CreateModel(
            name='QrsParticipantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.participantes')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.qrs')),
            ],
            options={
                'db_table': 'QrsParticipantes',
            },
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEntrada', models.DateTimeField()),
                ('fechaSalida', models.DateTimeField(null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.participantes')),
            ],
            options={
                'db_table': 'Asistencias',
            },
        ),
    ]
